name: adhui

channels:
    - pyviz
    - pyviz/label/dev
    - erdc
    - erdc/label/dev
    - aquaveo
    - conda-forge

dependencies:
    - python=3.6
    - panel
    - pyuit
    - holoviews
    - geoviews
    - xarray
    - param
    - numpy
    - genesis
    - pandas
    - geopandas
    - cartopy
    - xmsinterp
    - xmsmesh
    - datashader
    - adhmodel
    # for testing
    - pytest
    - pyflakes
    - nbsmoke
