name: adhui

channels:
    - pyviz/label/dev
    - pyviz
    - erdc/label/dev
    - erdc
    - aquaveo
    - conda-forge

dependencies:
    - python=3.6
    - panel>=0.6.0
    - pyuit
    - holoviews
    - geoviews
    - xarray
    - param
    - numpy
    - genesis>=0.0.5
    - pandas
    - geopandas
    - cartopy
    - xmsinterp
    - xmsmesh
    - datashader
    - adhmodel>=0.4.0
    # for testing
    - pytest
    - pyflakes
    - nbsmoke
